### ISSUE TITLE
I have problems

### ISSUE THREAD

**Issue by ashleyseattle** [ShalimaDeeljore/TryingOutGit#4]
@ShalimaDeeljore I have no idea what I am doing

**Comment by christinabru** [comment]
I agree, @Elizabm do you agree that @ashleyseattle has problems?

**Comment by Elizabm** [comment]
Hi Shalima…no action for me with these right?

Liz

**Comment by ShalimaDeeljore** [comment]
Nope sorry please disregard I’ve been doing some testing for the new acquisition

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Elizabm** [comment]
Okay, thanks.
